#! /bin/sh

# per chatgpt need to unset this for autorandr/postswitch to work
unset I3SOCK # ensure i3-msg finds the live socket

log="$HOME/.cache/autorandr.log"

case "$AUTORANDR_CURRENT_PROFILE" in
laptop)
    ~/setdpi laptop
    ;;
docked)
    ~/setdpi docked
    ;;
*)
    echo "$(date): no dpi rule set for $AUTORANDR_CURRENT_PROFILE" >>$log
    ;;
esac

# check if i3lock is running
if (pgrep --exact i3lock >/dev/null); then
    i3-msg reload # reload only b/c restart removes i3lock
else
    i3-msg restart
fi

# restart common programs that don't reset with dpi changes
if (pgrep --exact firefox >/dev/null); then
    pkill --exact firefox
    i3-msg 'workspace 1; exec firefox'
fi

if (pgrep --exact dunst >/dev/null); then
    pkill --exact dunst
    dunst &
fi

if (pgrep --exact 1password >/dev/null); then
    pkill --exact 1password
fi
