#!/usr/bin/env bash

# per chatgpt need to unset this for autorandr/postswitch to work
unset I3SOCK # ensure i3-msg finds the live socket

case "$1" in
laptop)
    xrdb -merge <<<"Xft.dpi: 162"
    ;;
docked)
    xrdb -merge <<<"Xft.dpi: 96"
    ;;
*)
    echo "Usage: $0 laptop | docked"
    exit 1
    ;;
esac
i3-msg restart
xrdb -query | grep -i Xft.dpi
